#                _        _____                _ _
#     /\        | |      / ____|              | | |
#    /  \  _   _| |_ ___| (___  _ __ ___   ___| | |_ ___ _ __
#   / /\ \| | | | __/ _ \\___ \| '_ ` _ \ / _ \ | __/ _ \ '__|
#  / ____ \ |_| | || (_) |___) | | | | | |  __/ | ||  __/ |
# /_/__  \_\__,_|\__\___/_____/|_| |_| |_|\___|_|\__\___|_|_ ___
# |  _ \            /\       | |            | |          /_ |__ \
# | |_) |_   _     /  \   ___| |__   ___  __| | ___  _ __ | |  ) |
# |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#         __/ |
#        |___/

# Setup here if you want a permission for this plugin | Put true if you want
Permission: "false"